# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dCondBiPois <- function(uu, vv, th1, th2, th12) {
    .Call(`_mtd_dCondBiPois`, uu, vv, th1, th2, th12)
}

pCondBiPois <- function(uu, vv, th1, th2, th12) {
    .Call(`_mtd_pCondBiPois`, uu, vv, th1, th2, th12)
}

pPMTD <- function(obs, lags, weight, la, ga) {
    .Call(`_mtd_pPMTD`, obs, lags, weight, la, ga)
}

rqrPMTD <- function(obs, weight, la, ga) {
    .Call(`_mtd_rqrPMTD`, obs, weight, la, ga)
}

pLMTD <- function(obs, lags, weight, alpha, phi) {
    .Call(`_mtd_pLMTD`, obs, lags, weight, alpha, phi)
}

rqrRegLMTD <- function(obs, xx, weight, bb, alpha, phi) {
    .Call(`_mtd_rqrRegLMTD`, obs, xx, weight, bb, alpha, phi)
}

updatePMTDut <- function(ut, dat, dep_lag, la, ga) {
    .Call(`_mtd_updatePMTDut`, ut, dat, dep_lag, la, ga)
}

updateNBMTDut <- function(ut, dat, dep_lag, th, alp, kap) {
    .Call(`_mtd_updateNBMTDut`, ut, dat, dep_lag, th, alp, kap)
}

updateGMTDlabel <- function(data, lags, mtdorder, weight, mu, sigma2, rho) {
    .Call(`_mtd_updateGMTDlabel`, data, lags, mtdorder, weight, mu, sigma2, rho)
}

updatePMTDlabel <- function(data, lags, mtdorder, weight, th, ut) {
    .Call(`_mtd_updatePMTDlabel`, data, lags, mtdorder, weight, th, ut)
}

updateNBMTDlabel <- function(data, lags, mtdorder, weight, th, ut, alp, kap) {
    .Call(`_mtd_updateNBMTDlabel`, data, lags, mtdorder, weight, th, ut, alp, kap)
}

updateLMTDlabel <- function(data, lags, mtdorder, weight, alpha, phi) {
    .Call(`_mtd_updateLMTDlabel`, data, lags, mtdorder, weight, alpha, phi)
}

predPMTD <- function(mtdorder, weight, lags, la, th, probs) {
    .Call(`_mtd_predPMTD`, mtdorder, weight, lags, la, th, probs)
}

predNBMTD <- function(mtdorder, weight, lags, th, psi, kap, probs) {
    .Call(`_mtd_predNBMTD`, mtdorder, weight, lags, th, psi, kap, probs)
}

